### ISSUE TITLE
python-pandas-read-csv-not-recognizing-t-in-tab-delimited-file

### ISSUE THREAD

**Issue by cameron2018** [zegami/image-similarity-clustering#3]
https://stackoverflow.com/questions/45443406/python-pandas-read-csv-not-recognizing-t-in-tab-delimited-file

**Comment by RogerNoble** [comment]
Hi @cameron2018. Just trying to understand the issue you are having. Does your tab file have C style escaped tab characters `\t` instead of an ASCII tab control character?
