### ISSUE TITLE
error: too few arguments

### ISSUE THREAD

**Issue by prolaser** [zegami/image-similarity-clustering#5]
Hi 
I would like to try your code for feature extraction on some images but I have faced a problem while running it. I have created the folder "images" as you mentioned and have put some images there. I have also created a .csv file with 2 columns id,image. While trying to run the script i pass the path of the .csv file but i get this error :  "error: too few arguments". This is what i write while trying to run your script, for example: python extract.py /home/user/image-similarity-clustering/example.csv
Please let me know if you know what is the problem.
Thank you

**Comment by RogerNoble** [comment]
Hi @prolaser,
Looks like there was a problem with how the defaults are set on the `model` argument. I've just made an update to address this.

You can now run `python extract.py /home/user/image-similarity-clustering/example.csv` without needing to specify the `model` argument.

I've also added a `requirements.txt` file to cover installing `Pillow`, `Pandas` and `h5py` as well as `Keras` and `Tensorflow`.

**Comment by prolaser** [comment]
Hi Roger

Thank you for the quick reply. It was really helpful and now the code is running fine. By the way your code is really straight forward and helpful for people like me who has just started working in this field. I appreciate your help.
