### ISSUE TITLE
Error : Initializing from file failed ?

### ISSUE THREAD

**Issue by JSKim0212** [zegami/image-similarity-clustering#6]
Hi. 

This is a great and simple example for unsupervised learning. Thank you so much.

By the way, I got an error, ' Initializing from file failed ' and 'Exception ignored in: <bound method BaseSession.del of <tensorflow.python.client.session.Session object at 0x00000139CF87C6A0>>
Traceback (most recent call last): File "C:\Users\DE\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\client\session.py", line 595, in __del__TypeError: 'NoneType' object is not callable' ,after printing 'lading named model'.

I ran this script : python extract.py meta inceptionv3,.
Under the meta folder, there are images folder and example.tsv file.
How can I fix the error?

**Comment by RogerNoble** [comment]
@JSKim0212 Looks like you're missing the path to the file. Instead of calling it with the directory name `meta` try with the file name.
`python extract.py example.tsv InceptionV3`
